
import os
import requests
import json

# API Key from environment or manual override
API_KEY = os.getenv("GEMINI_API_KEY", "AIzaSyDx75xTuxGUcDbVmN0D8ie8Ju9FMedpzT0")

def debug_400_error():
    if not API_KEY:
        print("Error: GEMINI_API_KEY not set.")
        return

    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
    
    headers = {
        "Content-Type": "application/json",
        "X-goog-api-key": API_KEY
    }
    
    # Payload similar to what might be generated by the app
    # This is a minimal valid payload
    payload = {
        "contents": [
            {
                "parts": [
                    {
                        "text": "Hello, how are you?"
                    }
                ]
            }
        ],
         "generationConfig": {"temperature": 0.1}
    }
    
    print(f"Testing Gemini API with model: gemini-2.0-flash")
    print(f"URL: {url}")
    print("Payload:", json.dumps(payload, indent=2))
    
    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        print("\nStatus Code:", response.status_code)
        print("Response:\n", json.dumps(response.json(), indent=2))
        print("✅ Simple request succeeded.")
    except requests.exceptions.RequestException as e:
        print(f"\n❌ Error: {e}")
        if hasattr(e, 'response') and e.response is not None:
             print("Response content:", e.response.text)

if __name__ == "__main__":
    debug_400_error()
